### ISSUE TITLE
Hand in "Lastenheft"

### ISSUE THREAD

**Issue by EnJoIsKaTe** [EnJoIsKaTe/ProjectFancy#1]
We have to hand in the "Lastenheft" to Mr. Heller until 12.01.2018 12:00 via Email. 
  
- [x] fill in the template sheet 
- [x] proofread by every member of the group
- [x] send the approved sheet to Mr. Heller  **IN TIME**

**Comment by bvogl** [comment]
We filled the template sheet, please proofread the thing so we can send it to Mr. Heller until this friday
 
- [x] approved by @xpanxnex 
- [x] approved by @EnJoIsKaTe 
- [x] approved by @PatrickKi 
- [x] approved by @bvogl

**Comment by EnJoIsKaTe** [comment]
Approved by me.

**Comment by bvogl** [comment]
We handed in the "Lastenheft" so now we're waiting for a possible feedback from Mr. Heller until we close this issue.

**Comment by bvogl** [comment]
The "Lastenheft" has been handed in successfully. Closing the issue.
