### ISSUE TITLE
Can't get UniversityId from DtQuestion

### ISSUE THREAD

**Issue by pklafs** [EnJoIsKaTe/ProjectFancy#15]
... the value is null. Maybe we have to use something like "navigation property"? (https://msdn.microsoft.com/en-us/library/jj679962(v=vs.113).aspx)

**Comment by pklafs** [comment]
- fixed the problem for FKs in DtQuestion
- still problems with FKs in DtUniversity

**Comment by bvogl** [comment]
it seems to be working now. close the issue if the bug is fixed please.
