### ISSUE TITLE
New Page for Creating a new Question

### ISSUE THREAD

**Issue by bvogl** [EnJoIsKaTe/ProjectFancy#16]
We need a new Page or if we wan´t to do it on a single page a new part of the page where we go to if the "Create new Question" - Button is clicked.

It has to contain a small text field to type the subject (Betreff) of the question and a big text box to type and edit the content of the question.

- [x] text field for the subject of the question
- [x] text box for the content of the question

**Comment by bvogl** [comment]
it´s all there and looking good

**Comment by pklafs** [comment]
I do agree gentlemen
