### ISSUE TITLE
Implement Responsive Design with Bootstrap

### ISSUE THREAD

**Issue by bvogl** [EnJoIsKaTe/ProjectFancy#23]
We have to use a more responsive Design for our Frontend Page.
We should stop using fixed sizes for our view-Elements so the Framework can format the view, when a mobile device is used.

For example we should use a GridLayout for our Views.

**Comment by pklafs** [comment]
Tutorial Example: https://www.w3schools.com/cSS/css_rwd_intro.asp

**Comment by pklafs** [comment]
did a first try at the homepage. as far as i can see, it looks good except the "create-button". now we have to do the same at the other pages

**Comment by PatrickKi** [comment]
Pages now fully support responsive design is nearly all resolutions.
