### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by pklafs** [EnJoIsKaTe/ProjectFancy#30]
implementing errrrrrror handling, especially for db-queries

**Comment by bvogl** [comment]
we should use a Exception Handling and write to a log-File

**Comment by pklafs** [comment]
i can do that in the next few days

**Comment by PatrickKi** [comment]
Added an Error-Page which can be redirected to in case of an error. As far as I know the links on the buttons that point to Home and CreateQuestion need to be added, buttons for that already exist.

**Comment by bvogl** [comment]
We now have exception handling implemented everywhere where we interact with the database. A logfile is written locally in the development environment to review exceptions.
