### ISSUE TITLE
Cleaning

### ISSUE THREAD

**Issue by pklafs** [EnJoIsKaTe/ProjectFancy#31]
just code cleaning and in addition check consistency and redundancy

**Comment by PatrickKi** [comment]
Deleted a lot of unnecessary code snippets.

**Comment by bvogl** [comment]
a lot of methods are still without comments. especially in the admincontroller and the accountcontroller

**Comment by bvogl** [comment]
added comments in the controller classes and reviewed older comments.
Seems to be just fine now.
