### ISSUE TITLE
Https

### ISSUE THREAD

**Issue by pklafs** [EnJoIsKaTe/ProjectFancy#32]
using of https

**Comment by EnJoIsKaTe** [comment]
Please post the link you mentioned.

**Comment by pklafs** [comment]
- for https we just have to add the attribute "RequireHttps" to controllers
- in addition the server must be configured
- if we want to use https while we develop, we have to set up iis (which means iis-express configuration in projects properties), but maybe this isn't necessary

**Comment by pklafs** [comment]
- I added Https
- please right-click the project 'XamPass' -> choose 'Properties' 'Debug' -> check 'EnableSSL' and copy the created link to 'App URL:'
- that's it

**Comment by pklafs** [comment]
- it seems to work without further configuration

**Comment by pklafs** [comment]
- set back to http according to problems with certificate of BA
