### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by pklafs** [EnJoIsKaTe/ProjectFancy#9]
Understanding of Unit Testing in ASP.NET Core MVC and implementation.

**Comment by bvogl** [comment]
we have now a folder for unit tests in our project.

**Comment by bvogl** [comment]
we implemented the first unit tests

**Comment by pklafs** [comment]
so it's time to close the issue?

**Comment by bvogl** [comment]
i will review the unit tests for the most up-to-date Version of the Application
